"""Ajout du modele Flashcard

Revision ID: 5b4983954d21
Revises: ab669aa48f8f
Create Date: 2026-08-11 18:45:40.351696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4983954d21'
down_revision = 'ab669aa48f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('reponse', sa.Text(), nullable=False),
    sa.Column('boite', sa.Integer(), nullable=True),
    sa.Column('prochaine_revision', sa.Date(), nullable=False),
    sa.Column('derniere_revision', sa.DateTime(), nullable=True),
    sa.Column('nb_revisions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcards')
    # ### end Alembic commands ###
