"""Ajout des modeles Projet, Tache et ActiviteJournaliere

Revision ID: 5d5fe59651dd
Revises: 5b4983954d21
Create Date: 2026-08-12 01:52:10.226585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5fe59651dd'
down_revision = '5b4983954d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('priorite', sa.String(length=10), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activites_journalieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('date_activite', sa.Date(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taches')
    op.drop_table('activites_journalieres')
    op.drop_table('projets')
    # ### end Alembic commands ###
