"""Ajout share_token pour partage en lecture seule

Revision ID: ab669aa48f8f
Revises: eb6a8d726120
Create Date: 2026-08-11 18:29:55.072378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab669aa48f8f'
down_revision = 'eb6a8d726120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_cer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_sessions_cer_share_token', ['share_token'])

    with op.batch_alter_table('sessions_revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_sessions_revision_share_token', ['share_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_revision', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sessions_revision_share_token', type_='unique')
        batch_op.drop_column('share_token')

    with op.batch_alter_table('sessions_cer', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sessions_cer_share_token', type_='unique')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
