"""Schema initial

Revision ID: eb6a8d726120
Revises: 
Create Date: 2026-08-07 18:12:23.549594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6a8d726120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('organisme', sa.String(length=100), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.Column('niveau_vise', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gratuite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_op', sa.String(length=50), nullable=False),
    sa.Column('nb_fichiers', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('annule', sa.Boolean(), nullable=True),
    sa.Column('rollback_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier', sa.String(length=500), nullable=False),
    sa.Column('mouvements', sa.Text(), nullable=False),
    sa.Column('nb_fichiers', sa.Integer(), nullable=True),
    sa.Column('annule', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions_cer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre_prosit', sa.String(length=300), nullable=False),
    sa.Column('numero_prosit', sa.String(length=50), nullable=True),
    sa.Column('etudiant', sa.String(length=200), nullable=False),
    sa.Column('pilote', sa.String(length=200), nullable=True),
    sa.Column('copilote', sa.String(length=200), nullable=True),
    sa.Column('promotion', sa.String(length=100), nullable=True),
    sa.Column('annee', sa.String(length=20), nullable=True),
    sa.Column('contexte', sa.Text(), nullable=False),
    sa.Column('besoins', sa.Text(), nullable=False),
    sa.Column('contraintes', sa.Text(), nullable=True),
    sa.Column('problematique', sa.Text(), nullable=False),
    sa.Column('plan_action', sa.Text(), nullable=False),
    sa.Column('realisation', sa.Text(), nullable=True),
    sa.Column('validation', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('bilan', sa.Text(), nullable=True),
    sa.Column('synthese', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('contenu_source', sa.Text(), nullable=True),
    sa.Column('latex_genere', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions_correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('type_doc', sa.String(length=50), nullable=False),
    sa.Column('contenu_source', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('reponse', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('matiere', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('domaine', sa.String(length=100), nullable=False),
    sa.Column('contenu_source', sa.Text(), nullable=True),
    sa.Column('cours_genere', sa.Text(), nullable=True),
    sa.Column('niveau_quiz', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('temps_sec', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ressources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type_ressource', sa.String(length=50), nullable=False),
    sa.Column('gratuit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ressources')
    op.drop_table('quiz_results')
    op.drop_table('sessions_revision')
    op.drop_table('sessions_qa')
    op.drop_table('sessions_correction')
    op.drop_table('sessions_cer')
    op.drop_table('organisation_snapshots')
    op.drop_table('file_operations')
    op.drop_table('certifications')
    # ### end Alembic commands ###
