"""Ajout du modele Parametre et des liens Tache vers Certification et CER

Revision ID: efd9fb996049
Revises: 5d5fe59651dd
Create Date: 2026-08-12 02:29:35.275867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd9fb996049'
down_revision = '5d5fe59651dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_taches_certification_id', 'certifications', ['certification_id'], ['id'])
        batch_op.create_foreign_key('fk_taches_cer_id', 'sessions_cer', ['cer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_taches_cer_id', type_='foreignkey')
        batch_op.drop_constraint('fk_taches_certification_id', type_='foreignkey')
        batch_op.drop_column('cer_id')
        batch_op.drop_column('certification_id')

    op.drop_table('parametres')
    # ### end Alembic commands ###
